apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-converter-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      components: converter
  template:
    metadata:
      labels:
        components: converter
    spec:
      containers:
        - name: conv-converter
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 3100
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_PASSWORD
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_QUEUE
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AMQP_HOSTNAME
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"